spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produtos-apirest
    username: gabriel
    password: gbr123!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true
    database: postgresql